In [2]:
import dotenv
import os
from sqlalchemy import create_engine
import pandas as pd

"QUESTe SONO LE CREDEDENZIALI CONTENUTE NEL FILE .ENV"
dotenv.load_dotenv() 
#dotenv.load_dotenv(override=True) #sovrascrive le variabili di sistema con quelle di ambiente tipo lo username

username=os.getenv("usernames")
password=os.getenv("password")
host=os.getenv("host")
dbname=os.getenv("dbname")


conn_string = f"mysql+pymysql://{username}:{password}@{host}/{dbname}"
print(conn_string)

db_engine = create_engine(conn_string)

query = """ SELECT *
            FROM dimproduct
        """
df = pd.read_sql(query, db_engine)
db_engine.dispose() #istruzione per chiudere il database
df

mysql+pymysql://studente_dapt:Ep1c0d3!!D4t4**4n4lys1s@epicode-data-pt-mysql.cvetyjye2qbl.eu-central-1.rds.amazonaws.com/AdventureWorksDW

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
1,2,BA-8327,NaN,None,None,Bearing Ball,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
2,3,BE-2349,NaN,None,None,BB Ball Bearing,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
3,4,BE-2908,NaN,None,None,Headset Ball Bearings,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
4,5,BL-2036,NaN,None,None,Blade,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,602,BB-8107,5.0,G,None,ML Bottom Bracket,Eje de pedalier GM,Axe de pédalier ML,44.95,1,...,铝合金车圈；大直径脚蹬轴。,فناجين من سبيكة الألومنيوم؛ ذات محور دوران كبي...,כיסויים מסגסוגת אלומיניום; ציר רחב-קוטר.,ดุมอลูมิเนียมอัลลอยด์ แกนเพลาขนาดใหญ่,Außenringe aus Aluminiumlegierung; Radachse mi...,アルミニウム合金カップ、大径スピンドル。,Alüminyum alaşımı orta göbekler; geniş çaplı mil.,2013-07-01,NaT,Current
602,603,BB-9108,5.0,G,None,HL Bottom Bracket,Eje de pedalier GA,Axe de pédalier HL,53.94,1,...,铝合金车圈和空心轴。,فناجين من سبيكة الألومنيوم ومحور أجوف.,כיסויים מסגסוגת אלומיניום וציר חלול.,ดุมอลูมิเนียมอัลลอยด์และเพลากลวง,Außenringe aus Aluminiumlegierung und hohle Ac...,アルミニウム合金カップとホロー アクスル。,Alüminyum alaşımı orta göbekler ve içi boş aks.,2013-07-01,NaT,Current
603,604,BK-R19B-44,2.0,LB,CM,"Road-750 Black, 44","Carretera: 750, negra, 44","Vélo de route 750 noir, 44",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current
604,605,BK-R19B-48,2.0,LB,CM,"Road-750 Black, 48","Carretera: 750, negra, 48","Vélo de route 750 noir, 48",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

In [5]:
#Estraiamo la tabella dimproduct dal database AdventureWorks, e valutiamo quanto segue:

#Quanti dati ci sono in totale?
numero_totale_dati = len(df)
numero_totale_dati

606

In [6]:
#Quali sono i metadati?
metadati = df.dtypes
metadati

ProductKey                        int64
ProductAlternateKey              object
ProductSubcategoryKey           float64
WeightUnitMeasureCode            object
SizeUnitMeasureCode              object
EnglishProductName               object
SpanishProductName               object
FrenchProductName                object
StandardCost                    float64
FinishedGoodsFlag                 int64
Color                            object
SafetyStockLevel                  int64
ReorderPoint                      int64
ListPrice                       float64
Size                             object
SizeRange                        object
Weight                          float64
DaysToManufacture                 int64
ProductLine                      object
DealerPrice                     float64
Class                            object
Style                            object
ModelName                        object
LargePhoto                       object
EnglishDescription               object
FrenchDescription                object
ChineseDescription               object
ArabicDescription                object
HebrewDescription                object
ThaiDescription                  object
GermanDescription                object
JapaneseDescription              object
TurkishDescription               object
StartDate                datetime64[ns]
EndDate                  datetime64[ns]
Status                           object
dtype: object

In [18]:
df.shape
df.columns #tutte le colonne
df.shape[0]#numero di righe
df.shape[1]#numero di colonne

36

In [22]:
#Stampiamo il primo elemento 
df.head(1)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

In [24]:
df.iloc[0] #ci restituisce tutti i valori dell'x elemento selezionato

ProductKey                                                               1
ProductAlternateKey                                                AR-5381
ProductSubcategoryKey                                                  NaN
WeightUnitMeasureCode                                                 None
SizeUnitMeasureCode                                                   None
EnglishProductName                                         Adjustable Race
SpanishProductName
FrenchProductName
StandardCost                                                           NaN
FinishedGoodsFlag                                                        0
Color                                                                   NA
SafetyStockLevel                                                      1000
ReorderPoint                                                           750
ListPrice                                                              NaN
Size                                                                  None
SizeRange                                                               NA
Weight                                                                 NaN
DaysToManufacture                                                        0
ProductLine                                                           None
DealerPrice                                                            NaN
Class                                                                 None
Style                                                                 None
ModelName                                                             None
LargePhoto               b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...
EnglishDescription                                                    None
FrenchDescription                                                     None
ChineseDescription                                                    None
ArabicDescription                                                     None
HebrewDescription                                                     None
ThaiDescription                                                       None
GermanDescription                                                     None
JapaneseDescription                                                   None
TurkishDescription                                                    None
StartDate                                              2003-07-01 00:00:00
EndDate                                                                NaT
Status                                                             Current
Name: 0, dtype: object

In [27]:
#Stampiamo l'ultimo elemento con tail
df.tail(1)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

In [28]:
#Stampiamo l'ultimo elemento con iloc
df.iloc[-1]

ProductKey                                                             606
ProductAlternateKey                                             BK-R19B-52
ProductSubcategoryKey                                                  2.0
WeightUnitMeasureCode                                                   LB
SizeUnitMeasureCode                                                     CM
EnglishProductName                                      Road-750 Black, 52
SpanishProductName                               Carretera: 750, negra, 52
FrenchProductName                               Vélo de route 750 noir, 52
StandardCost                                                        343.65
FinishedGoodsFlag                                                        1
Color                                                                Black
SafetyStockLevel                                                       100
ReorderPoint                                                            75
ListPrice                                                           539.99
Size                                                                    52
SizeRange                                                         48-52 CM
Weight                                                               20.42
DaysToManufacture                                                        4
ProductLine                                                              R
DealerPrice                                                        323.994
Class                                                                    L
Style                                                                    U
ModelName                                                         Road-750
LargePhoto               b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x8avw\xf7...
EnglishDescription       Entry level adult bike; offers a comfortable r...
FrenchDescription        Vélo d'adulte d'entrée de gamme ; permet une c...
ChineseDescription                       入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。
ArabicDescription        إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...
HebrewDescription        אופני מבוגרים למתחילים; מציעים רכיבה נוחה "מחו...
ThaiDescription          จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...
GermanDescription        Ein Erwachsenenrad für Einsteiger; bietet Komf...
JapaneseDescription      エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...
TurkishDescription       "Başlangıç seviyesinde yetişkin bisikleti, kır...
StartDate                                              2013-07-01 00:00:00
EndDate                                                                NaT
Status                                                             Current
Name: 605, dtype: object

In [30]:
#Riusciamo a stampare cinque elementi a caso?
df.sample(5)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
193,194,SA-T612,NaN,None,None,ML Touring Seat Assembly,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
411,412,FW-M928,17.0,None,None,HL Mountain Front Wheel,,,133.30,1,...,高性能的山地车备用轮。,عجلة احتياطية مخصصة للقيادة في الجبال عالية ال...,גלגל חלופי עתיר ביצועים לרכיבה הררית.,ล้ออะไหล่จักรยานภูเขาประสิทธิภาพสูง,Hochwertiges Ersatzrad für Mountainbikes.,高性能のマウンテン バイク用交換ホイール。,Yüksek performanslı yedek dağ bisikleti tekerl...,2012-07-01,2008-12-27,None
540,541,TI-T723,37.0,None,None,Touring Tire,Cubierta de paseo,Pneu de vélo de randonnée,10.84,1,...,高密度橡皮。,مطاط عالي الكثافة.,גומי בצפיפות גבוהה.,ยางความหนาแน่นสูง,Gummi mit hoher Dichte.,高密度ラバー。,Yüksek yoğunluklu lastik.,2013-07-01,NaT,Current
140,141,LR-8520,NaN,None,None,Lower Head Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
363,364,BK-M47B-38,1.0,LB,CM,"Mountain-300 Black, 38","Montaña: 300, negra, 38","VTT 300 noir, 38",598.44,1,...,适用于真正的越野车迷。此自行车极其耐用，无论身处何地，地形如何复杂，一切均在掌控之中，真正物...,لعاشقي قيادة الدراجات في الممرات غير الممهدة. ...,מתאימים למכורים לרכיבת שטח של ממש. אופניים עמי...,สำหรับนักปั่นทางวิบากตัวจริง เป็นจักรยานที่ทน...,"""Für echte Waldprofis. Ein extrem robustes Rad...",トレイルを愛するライダーのためのバイク。卓越した耐久性でどんな場所にも対応。難しい地形でもコ...,Gerçek kros tutkunlarına. Her yere gidebilen ...,2012-07-01,2008-12-27,None

In [37]:
#Quali sono i colori disponibili?
colori_disponibili = df['Color'].unique() #unique rimuove i duplicati
colori_disponibili

array(['NA', 'Black', 'Silver', 'Red', 'White', 'Blue', 'Multi', 'Yellow',
       'Grey', 'Silver/Black'], dtype=object)

In [36]:
#quanti sono i colori disponibili
numero_colori_disponibili = df['Color'].nunique() #nunique indica il numero dei dati senza duplicati
numero_colori_disponibili

10

In [44]:
#In media quanto pesano i prodotti?
peso_medio = df['Weight'].mean()
peso_medio

56.1932269503546

In [46]:
peso_minimo= df['Weight'].min()
peso_minimo

2.12

In [47]:
peso_massimo= df['Weight'].max()
peso_massimo

1050.0

In [49]:
#Quanti prodotti pesano più di 100 Kg?
peso_prod_100kg = df[df['Weight'] > 100].shape[0]
peso_prod_100kg

28

In [53]:
#Quanto costano in media i prodotti (colonna DealerPrice)?
media_prod_DealerPrice = df['DealerPrice'].mean().round(2)
media_prod_DealerPrice

448.6

In [54]:
#Se prendiamo un quarto di tutti i prodotti, 
#in modo che siano i più costosi, quale sarà il loro range di prezzo?

perc75 = df["DealerPrice"].quantile(0.75)

magg_perc75 = df[df["DealerPrice"] >= perc75]
range_start= magg_perc75["DealerPrice"].min()
range_end = magg_perc75["DealerPrice"].max()

print(f"Il range va da {range_start} a {range_end}")

Il range va da 722.5949 a 2146.962

In [61]:
#Qual è il prezzo medio per i prodotti di colore blu? 
prodotti_blu = df[df['Color'] == 'Blue']
prezzo_medio_blu = prodotti_blu['DealerPrice'].mean()
prezzo_medio_blu

516.0631785714286

In [64]:
#Qual è il prezzo medio per i prodotti di colore rosso o nero?
prodotti_neri_rossi = df[(df['Color'] == 'Red') | (df['Color'] == 'Black')] 

#in alternativa si può valutare anche
#prodotti_neri_rossi= df[df['Color'].isin(['Red','Black'])]

prezzo_medio_nero_rossi = prodotti_neri_rossi['DealerPrice'].mean()
prezzo_medio_nero_rossi

550.2481873684211

In [72]:
#Qual è il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg?
prodotti_taglia_42_peso_10 = df[(df['Size'] == '42') & (df['Weight'] >10)]
prezzo_max = prodotti_taglia_42_peso_10['DealerPrice'].max()
prezzo_max

2039.994

In [75]:
#Qual è il nome inglese e il costo di produzione (StandardCost) di tutti i prodotti di taglia 42,
#peso oltre i 10 Kg e colore argento?
print(df[(df["Size"] == "42") & (df["Weight"] <=10) & (df["Color"] == "Silver")][["EnglishProductName", "StandardCost"]])

                   EnglishProductName  StandardCost
287    HL Mountain Frame - Silver, 42        623.84
288    HL Mountain Frame - Silver, 42        660.91
289    HL Mountain Frame - Silver, 42        747.20
511  ML Mountain Frame-W - Silver, 42        199.38
523    LL Mountain Frame - Silver, 42        144.59

In [86]:
#ESERCIZIO AMAZON

df_amazon = pd.read_csv("amazon.csv")

#Valutiamo la dimensione del dataset 
print(f"dimensione dataset: {df_amazon.shape[0]} colonne, {df_amazon.shape[1]} righe")

dimensione dataset: 20000 colonne, 2 righe

In [87]:
#Visualizziamo dieci righe a caso; 
print(f"10 righe a caso:\n {df_amazon.sample(n=10)}\n\n")

10 righe a caso:
                                               reviewText  Positive
4953   For a tablet in business use you can't beat th...         1
10768  dont be upset about an app that says what it d...         1
19534  With the downfall of Google Reader Feedly real...         1
19088  A great time passer.  Haven't been playing it ...         1
8142   like watching funny flicks. help to take the s...         1
11605  Maxthon is fast and does everything I have tri...         1
16536  this is the first doctor who android based gam...         1
15117  wow, did anyone think to consider that the 're...         1
13176  This is definitely a five-star app.  Definitel...         1
9938   This game is super hard and really stupid. The...         0

In [83]:
#Osserviamo quali sono i nomi di colonna;
print(f"Colonne: {df_amazon.columns}")

Colonne: Index(['reviewText', 'Positive'], dtype='object')

In [85]:
#Il dataset è bilanciato, ovvero, il numero di 
#recensioni positive è uguale a quello delle negative, oppure no?
positive = df_amazon[df_amazon["Positive"] == True].count()
negative = df_amazon[df_amazon["Positive"] != True].count()

print(positive, negative, positive - negative)

reviewText    15233
Positive      15233
dtype: int64 reviewText    4767
Positive      4767
dtype: int64 reviewText    10466
Positive      10466
dtype: int64

In [92]:
#Esercizio: Il dataset diabetes.csv raccoglie persone con diabete o meno, 
#e il valore di diverse variabili fisiologiche dei pazienti.
df_diabetes = pd.read_csv("diabetes.csv")

#Osserviamone le dimensioni e un'anteprima di cinque righe;
df_diabetes.shape

(768, 9)

In [94]:
#Prendiamoci un po' di tempo per dare un'occhiata ai metadati delle colonne;
df_diabetes.dtypes

Number of times pregnant                                                      int64
Plasma glucose concentration a 2 hours in an oral glucose tolerance test      int64
Diastolic blood pressure (mm Hg)                                              int64
Triceps skin fold thickness (mm)                                              int64
2-Hour serum insulin (mu U/ml)                                                int64
Body mass index (weight in kg/(height in m)^2)                              float64
Diabetes pedigree function                                                  float64
Age (years)                                                                   int64
Class variable                                                                int64
dtype: object

In [95]:
#Stampiamo dei descrittori statistici del dataset; 
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Number of times pregnant                                                  768 non-null    int64
 1   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  768 non-null    int64
 2   Diastolic blood pressure (mm Hg)                                          768 non-null    int64
 3   Triceps skin fold thickness (mm)                                          768 non-null    int64
 4   2-Hour serum insulin (mu U/ml)                                            768 non-null    int64
 5   Body mass index (weight in kg/(height in m)^2)                            768 non-null    float64
 6   Diabetes pedigree function                                                768 non-null    float64
 7   Age (years)                                                               768 non-null    int64
 8   Class variable                                                            768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [99]:
#Selezioniamo i dati relativi a diverse fasce di età: <20, 20-30, 30-40, 40-50, >50;
#Qual è la media della pressione sanguigna diastolica per le diverse fasce di età? 

ranges = [0, 20, 30, 40, 50, 100]

data_collection = []

for index, num in enumerate(ranges[:-1]):
    
    data = df_diabetes[(df_diabetes["Age (years)"] > num) & (df_diabetes["Age (years)"] <= ranges[index + 1])][ "Diastolic blood pressure (mm Hg)"]
    data_collection.append(data)
    mean_for_range = data.mean()
    
    if num == 50:
        print(f"Media pressione diastolica in soggetti > 50 anni: {mean_for_range:.2f}")
        break
    
    print(f"Media pressione diastolica in fasce età tra {num} e {ranges[index + 1]}: {mean_for_range:.2f}\n")

Media pressione diastolica in fasce età tra 0 e 20: nan

Media pressione diastolica in fasce età tra 20 e 30: 65.32

Media pressione diastolica in fasce età tra 30 e 40: 70.27

Media pressione diastolica in fasce età tra 40 e 50: 74.79

Media pressione diastolica in soggetti > 50 anni: 78.38

In [100]:
#Qual è la media della pressione per ogni singolo anno di età?
start = df_diabetes["Age (years)"].min()
stop = df_diabetes["Age (years)"].max() + 1

for age in range(start, stop):
    
    pressure_mean = df_diabetes[df_diabetes['Age (years)'] == age][ 'Diastolic blood pressure (mm Hg)'].mean()
    print(f"Età {age}, Pressione Diastolica {pressure_mean:.2f}")

Età 21, Pressione Diastolica 65.94
Età 22, Pressione Diastolica 63.72
Età 23, Pressione Diastolica 64.32
Età 24, Pressione Diastolica 64.96
Età 25, Pressione Diastolica 59.67
Età 26, Pressione Diastolica 64.18
Età 27, Pressione Diastolica 73.50
Età 28, Pressione Diastolica 68.31
Età 29, Pressione Diastolica 68.24
Età 30, Pressione Diastolica 64.86
Età 31, Pressione Diastolica 64.38
Età 32, Pressione Diastolica 70.06
Età 33, Pressione Diastolica 65.65
Età 34, Pressione Diastolica 74.00
Età 35, Pressione Diastolica 75.60
Età 36, Pressione Diastolica 69.12
Età 37, Pressione Diastolica 75.95
Età 38, Pressione Diastolica 71.12
Età 39, Pressione Diastolica 72.67
Età 40, Pressione Diastolica 69.23
Età 41, Pressione Diastolica 67.59
Età 42, Pressione Diastolica 73.39
Età 43, Pressione Diastolica 78.46
Età 44, Pressione Diastolica 61.75
Età 45, Pressione Diastolica 83.07
Età 46, Pressione Diastolica 76.00
Età 47, Pressione Diastolica 78.33
Età 48, Pressione Diastolica 78.40
Età 49, Pressione Diastolica 81.40
Età 50, Pressione Diastolica 78.25
Età 51, Pressione Diastolica 84.50
Età 52, Pressione Diastolica 81.50
Età 53, Pressione Diastolica 79.00
Età 54, Pressione Diastolica 89.33
Età 55, Pressione Diastolica 70.25
Età 56, Pressione Diastolica 76.33
Età 57, Pressione Diastolica 76.80
Età 58, Pressione Diastolica 78.29
Età 59, Pressione Diastolica 74.00
Età 60, Pressione Diastolica 80.00
Età 61, Pressione Diastolica 76.00
Età 62, Pressione Diastolica 71.50
Età 63, Pressione Diastolica 78.00
Età 64, Pressione Diastolica 78.00
Età 65, Pressione Diastolica 78.67
Età 66, Pressione Diastolica 86.00
Età 67, Pressione Diastolica 72.67
Età 68, Pressione Diastolica 82.00
Età 69, Pressione Diastolica 81.00
Età 70, Pressione Diastolica 82.00
Età 71, Pressione Diastolica nan
Età 72, Pressione Diastolica 0.00
Età 73, Pressione Diastolica nan
Età 74, Pressione Diastolica nan
Età 75, Pressione Diastolica nan
Età 76, Pressione Diastolica nan
Età 77, Pressione Diastolica nan
Età 78, Pressione Diastolica nan
Età 79, Pressione Diastolica nan
Età 80, Pressione Diastolica nan
Età 81, Pressione Diastolica 74.00

In [102]:
#Il dataset insurance.csv contiene dati rispetto a caratteristiche e abitudini delle persone,
#e della zona in cui vivono, rispetto ai costi individuali per le cure mediche come premio per 
#le assicurazioni sulla salute. 
    
df_insurance = pd.read_csv("insurance.csv")
       
        • Quali sono le medie di charges rispetto a region? Ci sono differenze significative? 
        • E rispetto a smoker? E a sex? 
"""

"\n    Il dataset insurance.csv contiene dati rispetto a caratteristiche e abitudini delle persone,\n     e della zona in cui vivono, rispetto ai costi individuali per le cure mediche come premio per \n     le assicurazioni sulla salute. \n        • Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; \n        • Quali sono le medie di charges rispetto a region? Ci sono differenze significative? \n        • E rispetto a smoker? E a sex? \n"

In [106]:
#Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; 
df_insurance.shape
print(df_insurance.sample(4))
df_insurance.info()

      age     sex     bmi  children smoker     region      charges
27     55  female  32.775         2     no  northwest  12268.63225
1160   43  female  34.580         1     no  northwest   7727.25320
310    50    male  26.600         0     no  southwest   8444.47400
968    21    male  25.745         2     no  northeast   3279.86855
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [108]:
#Quali sono le medie di charges rispetto a region? Ci sono differenze significative?
print(df_insurance.groupby("region")["charges"].mean())

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

In [112]:
#E rispetto a smoker?
print(df_insurance.groupby("smoker")["charges"].mean())
#E a sex? 
print(df_insurance.groupby("sex")["charges"].mean())

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64
sex
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

In [113]:
# Il dataset pokemon.csv contiene un database di Pokémon, con dati quali 
# nome, tipi di attacco,valori di attacco/difesa/eccetera, e se sono o meno leggendari.

pokemon_df=pd.read_csv('pokemon.csv')

In [119]:
#Verifichiamo la dimensione
pokemon_df.shape

(800, 13)

In [121]:
#un'anteprima 
pokemon_df.sample(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
755,685,Slurpuff,Fairy,NaN,480,82,80,86,85,75,72,6,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
778,708,Phantump,Ghost,Grass,309,43,70,48,50,60,38,6,False

In [125]:
#ultimi 5 
pokemon_df.tail() #la prima colonna non può essere un'indice in quanto presenta dei duplicati

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [122]:
#osserviamo i nomi di colonna;
pokemon_df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [127]:
#Quali sono i Pokémon leggendari?
print(pokemon_df[pokemon_df["Legendary"]])

       #                 Name    Type 1    Type 2  Total   HP  Attack  \
156  144             Articuno       Ice    Flying    580   90      85
157  145               Zapdos  Electric    Flying    580   90      90
158  146              Moltres      Fire    Flying    580   90     100
162  150               Mewtwo   Psychic       NaN    680  106     110
163  150  MewtwoMega Mewtwo X   Psychic  Fighting    780  106     190
..   ...                  ...       ...       ...    ...  ...     ...
795  719              Diancie      Rock     Fairy    600   50     100
796  719  DiancieMega Diancie      Rock     Fairy    700   50     160
797  720  HoopaHoopa Confined   Psychic     Ghost    600   80     110
798  720   HoopaHoopa Unbound   Psychic      Dark    680   80     160
799  721            Volcanion      Fire     Water    600   80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
156      100       95      125     85           1       True
157       85      125       90    100           1       True
158       90      125       85     90           1       True
162       90      154       90    130           1       True
163      100      154      100    130           1       True
..       ...      ...      ...    ...         ...        ...
795      150      100      150     50           6       True
796      110      160      110    110           6       True
797       60      150      130     70           6       True
798       60      170      130     80           6       True
799      120      130       90     70           6       True

[65 rows x 13 columns]

In [128]:
#  E quali sono i leggendari di tipo 1 Grass? 

print(pokemon_df[(pokemon_df["Legendary"]) & (pokemon_df["Type 1"] == "Grass")])

       #               Name Type 1    Type 2  Total   HP  Attack  Defense  \
550  492  ShayminLand Forme  Grass       NaN    600  100     100      100
551  492   ShayminSky Forme  Grass    Flying    600  100     103       75
701  640           Virizion  Grass  Fighting    580   91      90       72

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
550      100      100    100           4       True
551      120       75    127           4       True
701       90      129    108           5       True

In [130]:
#E leggendari di tipo 1 Ice o Fire?
print(pokemon_df[(pokemon_df["Legendary"]) & (pokemon_df["Type 1"] == "Ice") | (pokemon_df["Type 1"] == "Fire")])

       #                       Name Type 1    Type 2  Total   HP  Attack  \
4      4                 Charmander   Fire       NaN    309   39      52
5      5                 Charmeleon   Fire       NaN    405   58      64
6      6                  Charizard   Fire    Flying    534   78      84
7      6  CharizardMega Charizard X   Fire    Dragon    634   78     130
8      6  CharizardMega Charizard Y   Fire    Flying    634   78     104
42    37                     Vulpix   Fire       NaN    299   38      41
43    38                  Ninetales   Fire       NaN    505   73      76
63    58                  Growlithe   Fire       NaN    350   55      70
64    59                   Arcanine   Fire       NaN    555   90     110
83    77                     Ponyta   Fire       NaN    410   50      85
84    78                   Rapidash   Fire       NaN    500   65     100
135  126                     Magmar   Fire       NaN    495   65      95
147  136                    Flareon   Fire       NaN    525   65     130
156  144                   Articuno    Ice    Flying    580   90      85
158  146                    Moltres   Fire    Flying    580   90     100
169  155                  Cyndaquil   Fire       NaN    309   39      52
170  156                    Quilava   Fire       NaN    405   58      64
171  157                 Typhlosion   Fire       NaN    534   78      84
236  218                     Slugma   Fire       NaN    250   40      40
237  219                   Magcargo   Fire      Rock    410   50      50
259  240                      Magby   Fire       NaN    365   45      75
263  244                      Entei   Fire       NaN    580  115     115
270  250                      Ho-oh   Fire    Flying    680  106     130
276  255                    Torchic   Fire       NaN    310   45      60
277  256                  Combusken   Fire  Fighting    405   60      85
278  257                   Blaziken   Fire  Fighting    530   80     120
279  257      BlazikenMega Blaziken   Fire  Fighting    630   80     160
352  322                      Numel   Fire    Ground    305   60      60
353  323                   Camerupt   Fire    Ground    460   70     100
354  323      CameruptMega Camerupt   Fire    Ground    560   70     120
355  324                    Torkoal   Fire       NaN    470   70      85
415  378                     Regice    Ice       NaN    580   80      50
435  390                   Chimchar   Fire       NaN    309   44      58
436  391                   Monferno   Fire  Fighting    405   64      78
437  392                  Infernape   Fire  Fighting    534   76     104
518  467                  Magmortar   Fire       NaN    540   75      95
542  485                    Heatran   Fire     Steel    600   91      90
557  498                      Tepig   Fire       NaN    308   65      63
558  499                    Pignite   Fire  Fighting    418   90      93
559  500                     Emboar   Fire  Fighting    528  110     123
572  513                    Pansear   Fire       NaN    316   50      53
573  514                   Simisear   Fire       NaN    498   75      98
614  554                   Darumaka   Fire       NaN    315   70      90
615  555    DarmanitanStandard Mode   Fire       NaN    480  105     140
616  555         DarmanitanZen Mode   Fire   Psychic    540  105      30
692  631                    Heatmor   Fire       NaN    484   85      97
721  653                   Fennekin   Fire       NaN    307   40      45
722  654                    Braixen   Fire       NaN    409   59      59
723  655                    Delphox   Fire   Psychic    534   75      69
730  662                Fletchinder   Fire    Flying    382   62      73
731  663                 Talonflame   Fire    Flying    499   78      81
735  667                     Litleo   Fire    Normal    369   62      50
736  668                     Pyroar   Fire    Normal    507   86      68
799  721                  Volcanion   Fire     Water    600   80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         43       60       50     65           1      False
5         58       80       65     80           1      False
6         78      109       85    100           1      False
7        111      130       85    100           1      False
8         78      159      115    100           1      False
42        40       50       65     65           1      False
43        75       81      100    100           1      False
63        45       70       50     60           1      False
64        80      100       80     95           1      False
83        55       65       65     90           1      False
84        70       80       80    105           1      False
135       57      100       85     93           1      False
147       60       95      110     65           1      False
156      100       95      125     85           1       True
158       90      125       85     90           1       True
169       43       60       50     65           2      False
170       58       80       65     80           2      False
171       78      109       85    100           2      False
236       40       70       40     20           2      False
237      120       80       80     30           2      False
259       37       70       55     83           2      False
263       85       90       75    100           2       True
270       90      110      154     90           2       True
276       40       70       50     45           3      False
277       60       85       60     55           3      False
278       70      110       70     80           3      False
279       80      130       80    100           3      False
352       40       65       45     35           3      False
353       70      105       75     40           3      False
354      100      145      105     20           3      False
355      140       85       70     20           3      False
415      100      100      200     50           3       True
435       44       58       44     61           4      False
436       52       78       52     81           4      False
437       71      104       71    108           4      False
518       67      125       95     83           4      False
542      106      130      106     77           4       True
557       45       45       45     45           5      False
558       55       70       55     55           5      False
559       65      100       65     65           5      False
572       48       53       48     64           5      False
573       63       98       63    101           5      False
614       45       15       45     50           5      False
615       55       30       55     95           5      False
616      105      140      105     55           5      False
692       66      105       66     65           5      False
721       40       62       60     60           6      False
722       58       90       70     73           6      False
723       72      114      100    104           6      False
730       55       56       52     84           6      False
731       71       74       69    126           6      False
735       58       73       54     72           6      False
736       72      109       66    106           6      False
799      120      130       90     70           6       True

In [133]:
#Ordiniamo il dataset per la colonna Name; 

pokemon_df = pokemon_df.sort_values(by='Name', ascending= True)

print(pokemon_df)

       #                     Name   Type 1  Type 2  Total   HP  Attack  \
510  460                Abomasnow    Grass     Ice    494   90      92
511  460  AbomasnowMega Abomasnow    Grass     Ice    594   90     132
68    63                     Abra  Psychic     NaN    310   25      20
392  359                    Absol     Dark     NaN    465   65     130
393  359          AbsolMega Absol     Dark     NaN    565   65     150
..   ...                      ...      ...     ...    ...  ...     ...
632  571                  Zoroark     Dark     NaN    510   60     105
631  570                    Zorua     Dark     NaN    330   40      65
46    41                    Zubat   Poison  Flying    245   40      45
695  634                 Zweilous     Dark  Dragon    420   72      85
794  718         Zygarde50% Forme   Dragon  Ground    600  108     100

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
510       75       92       85     60           4      False
511      105      132      105     30           4      False
68        15      105       55     90           1      False
392       60       75       60     75           3      False
393       60      115       60    115           3      False
..       ...      ...      ...    ...         ...        ...
632       60      120       60    105           5      False
631       40       80       40     65           5      False
46        35       30       40     55           1      False
695       70       65       70     58           5      False
794      121       81       95     95           6       True

[800 rows x 13 columns]

In [134]:
#Trasformiamo Name nell'indice;

pokemon_df.set_index("Name", inplace= True)
print(pokemon_df)

                           #   Type 1  Type 2  Total   HP  Attack  Defense  \
Name
Abomasnow                460    Grass     Ice    494   90      92       75
AbomasnowMega Abomasnow  460    Grass     Ice    594   90     132      105
Abra                      63  Psychic     NaN    310   25      20       15
Absol                    359     Dark     NaN    465   65     130       60
AbsolMega Absol          359     Dark     NaN    565   65     150       60
...                      ...      ...     ...    ...  ...     ...      ...
Zoroark                  571     Dark     NaN    510   60     105       60
Zorua                    570     Dark     NaN    330   40      65       40
Zubat                     41   Poison  Flying    245   40      45       35
Zweilous                 634     Dark  Dragon    420   72      85       70
Zygarde50% Forme         718   Dragon  Ground    600  108     100      121

                         Sp. Atk  Sp. Def  Speed  Generation  Legendary
Name
Abomasnow                     92       85     60           4      False
AbomasnowMega Abomasnow      132      105     30           4      False
Abra                         105       55     90           1      False
Absol                         75       60     75           3      False
AbsolMega Absol              115       60    115           3      False
...                          ...      ...    ...         ...        ...
Zoroark                      120       60    105           5      False
Zorua                         80       40     65           5      False
Zubat                         30       40     55           1      False
Zweilous                      65       70     58           5      False
Zygarde50% Forme              81       95     95           6       True

[800 rows x 12 columns]

In [135]:
# Quali sono i Pokémon della prima generazione con attacco > 50 e HP < 60?

pokemon_df =pokemon_df[(pokemon_df["Attack"] > 50) & (pokemon_df["HP"] < 60) & (pokemon_df["Generation"] == 1)]

print(pokemon_df)

              #    Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
Name
Bellsprout   69     Grass  Poison    300  50      75       35       70
Charmander    4      Fire     NaN    309  39      52       43       60
Charmeleon    5      Fire     NaN    405  58      64       58       80
Cloyster     91     Water     Ice    525  50      95      180       85
Diglett      50    Ground     NaN    265  10      55       25       35
Doduo        84    Normal  Flying    310  35      85       45       35
Dratini     147    Dragon     NaN    300  41      64       45       50
Dugtrio      51    Ground     NaN    405  35      80       50       50
Eevee       133    Normal     NaN    325  55      55       50       45
Ekans        23    Poison     NaN    288  35      60       44       40
Farfetch'd   83    Normal  Flying    352  52      65       55       58
Geodude      74      Rock  Ground    300  40      80      100       30
Goldeen     118     Water     NaN    320  45      67       60       35
Graveler     75      Rock  Ground    390  55      95      115       45
Growlithe    58      Fire     NaN    350  55      70       45       70
Hitmonchan  107  Fighting     NaN    455  50     105       79       35
Hitmonlee   106  Fighting     NaN    455  50     120       53       35
Kabuto      140      Rock   Water    355  30      80       90       55
Kingler      99     Water     NaN    475  55     130      115       50
Koffing     109    Poison     NaN    340  40      65       95       60
Krabby       98     Water     NaN    325  30     105       90       25
Magneton     82  Electric   Steel    465  50      60       95      120
Mankey       56  Fighting     NaN    305  40      80       35       35
Nidoran♂     32    Poison     NaN    273  46      57       40       40
Paras        46       Bug   Grass    285  35      70       55       45
Pikachu      25  Electric     NaN    320  35      55       40       50
Ponyta       77      Fire     NaN    410  50      85       55       65
Psyduck      54     Water     NaN    320  50      52       48       65
Raticate     20    Normal     NaN    413  55      81       60       50
Rattata      19    Normal     NaN    253  30      56       35       25
Sandshrew    27    Ground     NaN    300  50      75       85       20
Seadra      117     Water     NaN    440  55      65       95       95
Shellder     90     Water     NaN    305  30      65      100       45
Spearow      21    Normal  Flying    262  40      60       30       31
Wartortle     8     Water     NaN    405  59      63       80       65

            Sp. Def  Speed  Generation  Legendary
Name
Bellsprout       30     40           1      False
Charmander       50     65           1      False
Charmeleon       65     80           1      False
Cloyster         45     70           1      False
Diglett          45     95           1      False
Doduo            35     75           1      False
Dratini          50     50           1      False
Dugtrio          70    120           1      False
Eevee            65     55           1      False
Ekans            54     55           1      False
Farfetch'd       62     60           1      False
Geodude          30     20           1      False
Goldeen          50     63           1      False
Graveler         45     35           1      False
Growlithe        50     60           1      False
Hitmonchan      110     76           1      False
Hitmonlee       110     87           1      False
Kabuto           45     55           1      False
Kingler          50     75           1      False
Koffing          45     35           1      False
Krabby           25     50           1      False
Magneton         70     70           1      False
Mankey           45     70           1      False
Nidoran♂         40     50           1      False
Paras            55     25           1      False
Pikachu          50     90           1      False
Ponyta           65     90           1      False
Psyduck          50     55           1      False
Raticate         70     97           1      False
Rattata          35     72           1      False
Sandshrew        30     40           1      False
Seadra           45     85           1      False
Shellder         25     40           1      False
Spearow          31     70           1      False
Wartortle        80     58           1      False